{-# LANGUAGE LambdaCase        #-}
{-# LANGUAGE NoImplicitPrelude #-}

module Common.Keys where

import           Data.Either (Either (..))
import           Data.String (String)
import           Web.KeyCode (Key (..))

fromPlover :: String -> Either String Key
fromPlover = \case
  "BackSpace" -> Right Backspace
  "Tab"       -> Right Tab
  "Return"    -> Right Enter
  "Escape"    -> Right Escape
  "space"     -> Right Space
  "Page_Up"   -> Right PageUp
  "Page_Down" -> Right PageDown
  "End"       -> Right End
  "Home"      -> Right Home
  "Left"      -> Right ArrowLeft
  "Up"        -> Right ArrowUp
  "Right"     -> Right ArrowRight
  "Down"      -> Right ArrowDown
  "Insert"    -> Right Insert
  "Delete"    -> Right Delete
  "0"         -> Right Digit0
  "1"         -> Right Digit1
  "2"         -> Right Digit2
  "3"         -> Right Digit3
  "4"         -> Right Digit4
  "5"         -> Right Digit5
  "6"         -> Right Digit6
  "7"         -> Right Digit7
  "8"         -> Right Digit8
  "9"         -> Right Digit9
  "a"         -> Right KeyA
  "b"         -> Right KeyB
  "c"         -> Right KeyC
  "d"         -> Right KeyD
  "e"         -> Right KeyE
  "f"         -> Right KeyF
  "g"         -> Right KeyG
  "h"         -> Right KeyH
  "i"         -> Right KeyI
  "j"         -> Right KeyJ
  "k"         -> Right KeyK
  "l"         -> Right KeyL
  "m"         -> Right KeyM
  "n"         -> Right KeyN
  "o"         -> Right KeyO
  "p"         -> Right KeyP
  "q"         -> Right KeyQ
  "r"         -> Right KeyR
  "s"         -> Right KeyS
  "t"         -> Right KeyT
  "u"         -> Right KeyU
  "v"         -> Right KeyV
  "w"         -> Right KeyW
  "x"         -> Right KeyX
  "y"         -> Right KeyY
  "z"         -> Right KeyZ
  "F1"        -> Right F1
  "F2"        -> Right F2
  "F3"        -> Right F3
  "F4"        -> Right F4
  "F5"        -> Right F5
  "F6"        -> Right F6
  "F7"        -> Right F7
  "F8"        -> Right F8
  "F9"        -> Right F9
  "F10"       -> Right F10
  "F11"       -> Right F11
  "F12"       -> Right F12
  ";"         -> Right Semicolon
  "="         -> Right Equals
  ","         -> Right Comma
  "-"         -> Right Subtract
  "."         -> Right Period
  "/"         -> Right ForwardSlash
  "`"         -> Right Backquote
  "["         -> Right BracketLeft
  "\\"        -> Right Backslash
  "]"         -> Right BracketRight
  "'"         -> Right Apostrophe
  str         -> Left str
