name: CMS Content Update
run-name: ${{ github.actor }} pushed/looking for changes in cms-content
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: get changed files in the folder cms-content
        id: cms
        uses: tj-actions/changed-files@v35.6.1
        with:
          files: cms-content/**
          json: true

      - name: web request to invalidate cache
        if: steps.cms.outputs.any_changed == 'true'
        run: |
          set -x
          echo "Changed files:"
          echo "${{steps.cms.outputs.all-changed-files}}"
          for file in ${{steps.cms.outputs.all-changed-files}}
          do
            echo $file
          done
          curl -X POST https://palantype.com/api/cms/invalidate-cache \
               -H "Content-Type: application/json" \
               -d "\"${{steps.cms.outputs.all-changed-files}}\""
